from dataclasses import dataclass

from financial_bot.app.domain.types import CategoryOwnerRole


@dataclass(frozen=True, slots=True)
class CategorySeed:
    code: str
    title: str
    owner_role: CategoryOwnerRole
    sort_order: int
    is_expense: bool = True
    is_active: bool = True


@dataclass(frozen=True, slots=True)
class CategoryAliasSeed:
    alias: str
    category_code: str


DEFAULT_CATEGORIES: tuple[CategorySeed, ...] = (
    CategorySeed(
        code="utilities",
        title="ЖКХ",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=1,
    ),
    CategorySeed(
        code="groceries",
        title="Продукты",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=2,
    ),
    CategorySeed(
        code="subscriptions_communications",
        title="Подписки/Связь/Интернет",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=3,
    ),
    CategorySeed(
        code="auto",
        title="Авто (бензин, базовое ТО)",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=4,
    ),
    CategorySeed(
        code="pets",
        title="Питомцы",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=5,
    ),
    CategorySeed(
        code="restaurants_cafes",
        title="Рестораны/Кафе",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=6,
    ),
    CategorySeed(
        code="kids_education_sport",
        title="Дети (Образование/Спорт)",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=7,
    ),
    CategorySeed(
        code="cosmetology_medicine",
        title="Косметология/Медицина",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=8,
    ),
    CategorySeed(
        code="clothing_shoes",
        title="Одежда/Обувь",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=9,
    ),
    CategorySeed(
        code="fitness_sport",
        title="Фитнес/Спорт",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=10,
    ),
    CategorySeed(
        code="hobbies",
        title="Хобби",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=11,
    ),
    CategorySeed(
        code="home_land",
        title="Дом/Участок",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=12,
    ),
    CategorySeed(
        code="gifts_entertainment_holidays",
        title="Подарки/Развлечения/Праздники",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=13,
    ),
    CategorySeed(
        code="travel_vacation",
        title="Путешествия/Отдых",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=14,
    ),
    CategorySeed(
        code="investments_savings",
        title="Инвестиции/Накопления",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=15,
    ),
    CategorySeed(
        code="help_reserve",
        title="Помощь/Резерв",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=16,
    ),
    CategorySeed(
        code="taxes",
        title="Налоги",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=17,
    ),
    CategorySeed(
        code="internal_transfer",
        title="Самоперевод / внутренний перевод",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=99,
        is_expense=False,
    ),
    CategorySeed(
        code="income_general",
        title="Доходы",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=100,
        is_expense=False,
    ),
    CategorySeed(
        code="income_salary",
        title="Зарплата",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=101,
        is_expense=False,
    ),
    CategorySeed(
        code="income_advance",
        title="Аванс",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=102,
        is_expense=False,
    ),
    CategorySeed(
        code="income_bonus",
        title="Премия/Бонус",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=103,
        is_expense=False,
    ),
    CategorySeed(
        code="income_business",
        title="Бизнес/Проекты",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=104,
        is_expense=False,
    ),
    CategorySeed(
        code="income_debt_return",
        title="Возврат долга",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=105,
        is_expense=False,
    ),
    CategorySeed(
        code="income_other",
        title="Прочий доход",
        owner_role=CategoryOwnerRole.SYSTEM,
        sort_order=106,
        is_expense=False,
    ),
)


DEFAULT_CATEGORY_ALIASES: tuple[CategoryAliasSeed, ...] = (
    CategoryAliasSeed("жкх", "utilities"),
    CategoryAliasSeed("коммуналка", "utilities"),
    CategoryAliasSeed("коммунальные", "utilities"),
    CategoryAliasSeed("квартплата", "utilities"),
    CategoryAliasSeed("свет", "utilities"),
    CategoryAliasSeed("вода", "utilities"),
    CategoryAliasSeed("газ", "utilities"),
    CategoryAliasSeed("отопление", "utilities"),
    CategoryAliasSeed("электричество", "utilities"),
    CategoryAliasSeed("продукты", "groceries"),
    CategoryAliasSeed("продукт", "groceries"),
    CategoryAliasSeed("супермаркет", "groceries"),
    CategoryAliasSeed("магнит", "groceries"),
    CategoryAliasSeed("пятерочка", "groceries"),
    CategoryAliasSeed("пятёрочка", "groceries"),
    CategoryAliasSeed("лента", "groceries"),
    CategoryAliasSeed("мясной", "groceries"),
    CategoryAliasSeed("подписки", "subscriptions_communications"),
    CategoryAliasSeed("подписка", "subscriptions_communications"),
    CategoryAliasSeed("связь", "subscriptions_communications"),
    CategoryAliasSeed("интернет", "subscriptions_communications"),
    CategoryAliasSeed("телефон", "subscriptions_communications"),
    CategoryAliasSeed("мобильная связь", "subscriptions_communications"),
    CategoryAliasSeed("мтс", "subscriptions_communications"),
    CategoryAliasSeed("билайн", "subscriptions_communications"),
    CategoryAliasSeed("мегафон", "subscriptions_communications"),
    CategoryAliasSeed("теле2", "subscriptions_communications"),
    CategoryAliasSeed("авто", "auto"),
    CategoryAliasSeed("машина", "auto"),
    CategoryAliasSeed("бензин", "auto"),
    CategoryAliasSeed("азс", "auto"),
    CategoryAliasSeed("топливо", "auto"),
    CategoryAliasSeed("техобслуживание", "auto"),
    CategoryAliasSeed("питомцы", "pets"),
    CategoryAliasSeed("питомец", "pets"),
    CategoryAliasSeed("кот", "pets"),
    CategoryAliasSeed("кошка", "pets"),
    CategoryAliasSeed("собака", "pets"),
    CategoryAliasSeed("корм", "pets"),
    CategoryAliasSeed("ветеринар", "pets"),
    CategoryAliasSeed("ветклиника", "pets"),
    CategoryAliasSeed("рестораны", "restaurants_cafes"),
    CategoryAliasSeed("ресторан", "restaurants_cafes"),
    CategoryAliasSeed("кафе", "restaurants_cafes"),
    CategoryAliasSeed("доставка", "restaurants_cafes"),
    CategoryAliasSeed("кофейня", "restaurants_cafes"),
    CategoryAliasSeed("дети", "kids_education_sport"),
    CategoryAliasSeed("ребенок", "kids_education_sport"),
    CategoryAliasSeed("ребёнок", "kids_education_sport"),
    CategoryAliasSeed("образование", "kids_education_sport"),
    CategoryAliasSeed("школа", "kids_education_sport"),
    CategoryAliasSeed("сад", "kids_education_sport"),
    CategoryAliasSeed("садик", "kids_education_sport"),
    CategoryAliasSeed("кружок", "kids_education_sport"),
    CategoryAliasSeed("секция", "kids_education_sport"),
    CategoryAliasSeed("косметология", "cosmetology_medicine"),
    CategoryAliasSeed("медицина", "cosmetology_medicine"),
    CategoryAliasSeed("здоровье", "cosmetology_medicine"),
    CategoryAliasSeed("врач", "cosmetology_medicine"),
    CategoryAliasSeed("аптека", "cosmetology_medicine"),
    CategoryAliasSeed("аптеки", "cosmetology_medicine"),
    CategoryAliasSeed("лекарства", "cosmetology_medicine"),
    CategoryAliasSeed("стоматология", "cosmetology_medicine"),
    CategoryAliasSeed("красота", "cosmetology_medicine"),
    CategoryAliasSeed("одежда", "clothing_shoes"),
    CategoryAliasSeed("обувь", "clothing_shoes"),
    CategoryAliasSeed("вещи", "clothing_shoes"),
    CategoryAliasSeed("фитнес", "fitness_sport"),
    CategoryAliasSeed("спорт", "fitness_sport"),
    CategoryAliasSeed("зал", "fitness_sport"),
    CategoryAliasSeed("тренировка", "fitness_sport"),
    CategoryAliasSeed("бассейн", "fitness_sport"),
    CategoryAliasSeed("хобби", "hobbies"),
    CategoryAliasSeed("дом", "home_land"),
    CategoryAliasSeed("участок", "home_land"),
    CategoryAliasSeed("ремонт", "home_land"),
    CategoryAliasSeed("стройка", "home_land"),
    CategoryAliasSeed("дача", "home_land"),
    CategoryAliasSeed("мебель", "home_land"),
    CategoryAliasSeed("хозтовары", "home_land"),
    CategoryAliasSeed("подарки", "gifts_entertainment_holidays"),
    CategoryAliasSeed("подарок", "gifts_entertainment_holidays"),
    CategoryAliasSeed("развлечения", "gifts_entertainment_holidays"),
    CategoryAliasSeed("праздник", "gifts_entertainment_holidays"),
    CategoryAliasSeed("праздники", "gifts_entertainment_holidays"),
    CategoryAliasSeed("кино", "gifts_entertainment_holidays"),
    CategoryAliasSeed("театр", "gifts_entertainment_holidays"),
    CategoryAliasSeed("цветы", "gifts_entertainment_holidays"),
    CategoryAliasSeed("букет", "gifts_entertainment_holidays"),
    CategoryAliasSeed("путешествия", "travel_vacation"),
    CategoryAliasSeed("путешествие", "travel_vacation"),
    CategoryAliasSeed("отдых", "travel_vacation"),
    CategoryAliasSeed("отпуск", "travel_vacation"),
    CategoryAliasSeed("поездка", "travel_vacation"),
    CategoryAliasSeed("билеты", "travel_vacation"),
    CategoryAliasSeed("отель", "travel_vacation"),
    CategoryAliasSeed("гостиница", "travel_vacation"),
    CategoryAliasSeed("инвестиции", "investments_savings"),
    CategoryAliasSeed("инвестиция", "investments_savings"),
    CategoryAliasSeed("накопления", "investments_savings"),
    CategoryAliasSeed("накопить", "investments_savings"),
    CategoryAliasSeed("вклад", "investments_savings"),
    CategoryAliasSeed("брокер", "investments_savings"),
    CategoryAliasSeed("акции", "investments_savings"),
    CategoryAliasSeed("облигации", "investments_savings"),
    CategoryAliasSeed("помощь", "help_reserve"),
    CategoryAliasSeed("резерв", "help_reserve"),
    CategoryAliasSeed("перевод", "help_reserve"),
    CategoryAliasSeed("переводы", "help_reserve"),
    CategoryAliasSeed("чаевые", "help_reserve"),
    CategoryAliasSeed("налог", "taxes"),
    CategoryAliasSeed("налоги", "taxes"),
    CategoryAliasSeed("ндфл", "taxes"),
    CategoryAliasSeed("имущественный налог", "taxes"),
    CategoryAliasSeed("транспортный налог", "taxes"),
    CategoryAliasSeed("земельный налог", "taxes"),
    CategoryAliasSeed("сам себе", "internal_transfer"),
    CategoryAliasSeed("себе", "internal_transfer"),
    CategoryAliasSeed("самоперевод", "internal_transfer"),
    CategoryAliasSeed("внутренний перевод", "internal_transfer"),
)
